name: Deploy CocoaPods

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push --allow-warnings NuguUtils.podspec
          pod trunk push --synchronous --allow-warnings NuguObjcUtils.podspec
          pod trunk push --synchronous --allow-warnings NuguCore.podspec
          pod trunk push --synchronous --allow-warnings TycheSDK.podspec
          pod trunk push --synchronous --allow-warnings JadeMarble.podspec
          pod trunk push --synchronous --allow-warnings KeenSense.podspec
          pod trunk push --synchronous --allow-warnings OpusSDK.podspec
          pod trunk push --synchronous --allow-warnings SilverTray.podspec
          pod trunk push --synchronous --allow-warnings NuguAgents.podspec
          pod trunk push --synchronous --allow-warnings NuguServiceKit.podspec
          pod trunk push --synchronous --allow-warnings NuguUIKit.podspec
          pod trunk push --synchronous --allow-warnings NuguLoginKit.podspec
          pod trunk push --synchronous --allow-warnings NuguClientKit.podspec

        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
